### ISSUE TITLE
Figure out what postfix does with simultaneous "encrypt" and a cert Subject name constraint

### ISSUE THREAD

**Issue by pde** [EFForg/starttls-everywhere#2]

**Comment by dkg** [comment]
I think the first part of this question means "if `smtp_tls_policy_maps` looks up the destination domain and finds `encrypt`".  I'm not sure what the second part means.  Are we talking about a [nameConstraint](https://tools.ietf.org/html/rfc5280#section-4.2.1.10) placed on the issuing CA for the certificate provided by the remote endpoint?  if so, is the name constraint intended to scope the destination domain, or the name of the receiving mail exchanger?  is the question about when the name constraint does not match the subjectAltName of the end entity certificate, or about some other circumstance?

**Comment by pde** [comment]
I don't remember exactly what I was thinking when I filed this ;), but I could have been trying to figure out whether the cert subject name check would:

1. happen
2. be backed by any cert checking (if we wanted to use it as a means of pinning a specific CA or set of CAs)

Probably if 2 is not true there wouldn't be much you could usefully do with this.

**Comment by pde** [comment]
o:

 3. if 1 and 2 were true perhaps use it to work around issues with servers that have a valid cert, but not for all of their email domains.

**Comment by sydneyli** [comment]
The [`secure` security level](http://www.postfix.org/TLS_README.html#client_tls_secure) allows you to require verification and configure what name is used to check against the cert's CN or SANs, and there's a way to configure [per-domain CA-pinning](http://www.postfix.org/postconf.5.html#smtp_tls_trust_anchor_file) since Postfix 2.11. These seem to address the above questions, so I'll close this issue for now; if I've misunderstood, feel free to re-open.
