### ISSUE TITLE
Switching File Formats

### ISSUE THREAD

**Issue by azet** [EFForg/starttls-everywhere#32]
JSON with comments is nice, but not an approved standard - we should probably switch to something that's universally used and maybe a bit more terse in the future (low priority).

What do you think? @pde @dmwilcox 

Suggestions?

Aaron

**Comment by KevinMartin** [comment]
I think JSON is great. I don't get why we need comments in the JSON, though.

To play devils advocate though... If comments are a problem for you, you can:
- Not add comments to your file or
- Parse the file, removing the comments

**Comment by dmwilcox** [comment]
Changing formats isn't hard, it could easily be switched to something else,
such as YAML.

BTW, I never put in the libraries to allow proper Javascript comments in
the config file -- instead I just added another 'comment' data field.  In
order words -- it is just a JSON file.  (pde@ and I talked about this but
it should be reflected in the documentation)

There hasn't been much of a rush on the side of coordination but the
intention with the Config object is to be able to get configuration files
from various big mail providers and concatenate them together quite simply.
Since they can't literally be concatenated 'cat *.json > big.json' style.

A format such as YAML may handle that task more simply and the update/merge
code could be relegated for the purposes of advanced users creating
overrides, or removed.

Daniel

On Fri, Apr 29, 2016 at 8:16 AM, Kevin Jose Martin <notifications@github.com

**Comment by azet** [comment]
YAML has the whitespace problem. Also if these files get big we may need something that's more.. 'binary'. What about CBOR? http://cbor.io/

**Comment by dmwilcox** [comment]
CBOR looks nice.  If we end up going the route of distributing LE MTA certs
fingerprints to each other handling the larger numbers would be good.
Python seems to have a couple implementations so we're set there as well.

Ultimately if we distribute something like this we'll want to sign it as
well and have a process for getting *that* public key out there, in
addition to the https transit to attempt to 'root' trust of the MTA
fingerprints.  It's not that JSON or YAML can't be malicious... but it sure
is easier to tell when you open the file and look at it (you know... with
your eyes)... a binary file format not so much.

I'm a little wary to jump on this too early -- we should figure out what
our priorities are in a rough order.  However if we can get the ISRG guys
to help with handling a PGP key for signing, or at least start that
conversation, that would make things easier on the distributing trustworthy
MTA fingerprints front.

**Comment by azet** [comment]
BTW. the ACME protocol that Let's Encrypt uses makes use of JOSE (JSON Object Signing and Encryption), there's a similar standard for CBOR called "COSE" if we, at some point, need to sign or even encrypt CBOR "Objects" for transmission over various channels.

**Comment by azet** [comment]
Feedback I got for CBOR in UTA so far has been: little deployment, extra barrier, nobody really uses it / knows if it's secure enough. I'm worried about that myself.

Any suggestions for very simple binary representations that would fit our goals?

**Comment by azet** [comment]
protobufs has been suggested, but since it isn't an IETF standard, it's unlikely we'll end up with that in UTA-WG and related documents. For now they stick to plain JSON.
