### ISSUE TITLE
Add TLS protocols to the policy list

### ISSUE THREAD

**Issue by rlaager** [EFForg/starttls-everywhere#80]
It would be nice if the policy list included the versions of TLS supported. This would allow requiring TLS 1.2 (or TLS 1.3) for domains that support it, without needing to require TLS 1.2 for all domains in the policy list.

An implementation might be for the policy list to include the highest version of TLS supported. Then the postfix integration should invert that. For example, if a domain supports TLS 1.2 in the policy list, the Postfix policy map should have "protocols=!SSLv2:!SSLv3:!TLSv1:!TLSv1.1". In this way, downgrades are prevented, but the policy map does not preclude a newer version from being used. If the site starts supporting TLS 1.3, it can be instantly used without needing a policy update.

**Comment by rlaager** [comment]
Fair enough that TLS 1.2 is the minimum right now. That doesn’t really change the motivation here. If the policy list tracked a version, then the MTA policy could require 1.3 for domains that support it, without requiring 1.3 for all domains.

**Comment by hardfalcon** [comment]
I still don't see why you'd put that information into the StartTLS-Everywhere policy list. TLS implementations are supposed to always negotiate the highest possible TLS version, even without any external policy list. Some older TLS implementations didn't perform that negotiation correctly, which is why `TLS_FALLBACK_SCSV` was introduced with [RFC 7507](https://tools.ietf.org/html/rfc7507). I think it's safe to assume that admins making the extra effort of deploying MTA-STS will also make sure that they are using a TLS implementation that supports TLS_FALLBACK_SCSV.

**Comment by rlaager** [comment]
The point of putting the version in the policy is so I can require at least that version, to avoid downgrade attacks. However, as you say, that is what `TLS_FALLBACK_SCSV` is for, so I guess we can consider downgrade attacks a solved problem.
